name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Rspec
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Rspec
        run: bin/rspec --format documentation
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '75 90'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
  brakeman:
    runs-on: ubuntu-latest
    name: Brakeman
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Breakman
        run: bin/brakeman --run-all-checks --force --no-exit-on-warn --quiet --no-pager --no-color

  standardrb:
    runs-on: ubuntu-latest
    name: StandardRb
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: StandardRB
        run: bin/standardrb --no-fix -f github

